### ISSUE TITLE
Warnings and Errors with Julia 0.4

### ISSUE THREAD

**Issue by m-ender** [pao/StrPack.jl#21]
I was trying to use this package with Julia 0.4, but on top of tons of deprecation warnings, it throws an error when actually trying use `pack` or `unpack`.

When loading the package, there is a flood of warnings along the lines of

```
WARNING: Base.Uint is deprecated, use UInt instead.
  likely near C:\Users\buettner\.julia\v0.4\StrPack\src\StrPack.jl:397
```

Once I use `@struct`, there are more of these:

```
WARNING: Base.String is deprecated, use AbstractString instead.
[...]
in pack at C:\Users\buettner\.julia\v0.4\StrPack\src\StrPack.jl:204
```

And then when I try `pack` or `unpack` I get:

```
ERROR: LoadError: type DataType has no field names
 in chktype at C:\Users\buettner\.julia\v0.4\StrPack\src\StrPack.jl:136
 in pack at C:\Users\buettner\.julia\v0.4\StrPack\src\StrPack.jl:197
 in pack at C:\Users\buettner\.julia\v0.4\StrPack\src\StrPack.jl:241
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in process_options at client.jl:308
 in _start at client.jl:411
while loading [pathtomycode]\crom.jl, in expression starting on line 22
```

**Comment by ararslan** [comment]
I can confirm that this happens simply by executing the example code on ReadTheDocs.

**Comment by pao** [comment]
See also #17.

**Comment by DanielArndt** [comment]
@pao Are you considering tagging a new version? It looks like some of these warnings / errors have been resolved.

**Comment by erfangc** [comment]
:+1: please tag a new version the last is from more than a year ago and breaks with `0.4+` @pao thank you for the code!

**Comment by helgee** [comment]
:+1:

**Comment by breichholf** [comment]
:+1: for tagging a new version

**Comment by thomas-nilsson-irfu** [comment]
:+1: I would also like to see a new released version with this issue fixed. Soon two years will have passed since the last release.

**Comment by aviks** [comment]
v0.1.0 supporting 0.5 was tagged some time ago.
